default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  encoding: unicode
  username: postgres
  password: 12345678
  
development:
  <<: *default
  database: damian_development

test:
  <<: *default
  database: damian_test

production:
  <<: *default
  database: damian_production
